### ISSUE TITLE
[BUG] Generate Image for character creation broken

### ISSUE THREAD

**Issue by MichaelJHTaggart** [EwanStubblefield-Allen/Dragon_Dungeons#14]
# Generate Image for character creation broken
https://dragons.ewanstubblefield-allen.dev/?code=######/create-character/basics

## Description
A clear and detailed explanation of the issue. Include any relevant details like:

- What you were trying to do?
I was attempting to utilize the "Generate Image" button on the Create Character page.

- The expected outcome.
I can click the plus button on the right hand side of the "Generate Character Picture:" field to generate an image.

- The actual outcome.
We receive a 400 and are not able to generate an image. 

![Screenshot 2024-01-27 170034](https://github.com/EwanStubblefield-Allen/Dragon_Dungeons/assets/63270278/c427f9a1-f5f9-41e5-9ca6-cf73cac5c032)

## Steps to Reproduce
List the steps to reproduce the behavior:
1. Go to [https://dragons.ewanstubblefield-allen.dev/](https://dragons.ewanstubblefield-allen.dev/)
2. Click on "Create Character"
3. Fill out all fields, and attempt to generate an image.

## Environment
Provide details about your environment:
- Browser: Chrome
- Version 120.0.6099.225 (Official Build) (64-bit)

## Possible Solution 
Check connectivity to the service here: src/services/OpenService.js to see if we are getting back what we need to get back.

**Comment by EwanStubblefield-Allen** [comment]
Updated open AI api key by creating a new account.
